// Generated by mpgen from /home/cory/dev/bitcoin/src/ipc/capnp/common.capnp

#include <src/ipc/capnp/common.capnp.proxy-types.h>
#include <mp/proxy-types.h>

namespace mp {
namespace {
} // namespace
} // namespace mp
